Resources:
  StarwarsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StarwarsLambdaRole${self:custom.version}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com

  StarwarsLambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: StarwarsLambdaPolicy${self:custom.version}
      Description: Permisos.
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:Scan
              - dynamodb:Query
            Effect: Allow
            Resource: "*"
      Roles:
        - !Ref StarwarsLambdaRole

  FusionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.FusionTable}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: pk,       AttributeType: S }
        - { AttributeName: sk,       AttributeType: N }
        - { AttributeName: planetId, AttributeType: N }   # para el GSI
      KeySchema:
        - { AttributeName: pk, KeyType: HASH }
        - { AttributeName: sk, KeyType: RANGE }
      GlobalSecondaryIndexes:
        - IndexName: PlanetIdIndex
          KeySchema:
            - { AttributeName: planetId, KeyType: HASH }
            - { AttributeName: sk,       KeyType: RANGE }
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  AlmacenadosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.AlmacenadosTable}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH